name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Verify AWS_S3_BUCKET
      run: echo "AWS_S3_BUCKET is $AWS_S3_BUCKET"
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete
        source_dir: 'dist'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-northeast-2"

    - name: Invalidate CloudFront cache
      uses: chetan/invalidate-cloudfront-action@v1
      with:
        distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        paths: "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}